export const FREE_SSL_PERIOD_DAYS = [
  {
    value: "90",
    label: "90 days days (3 months)",
  },
];
export const OTHER_SSL_PERIOD_DAYS = [
  { value: "365", label: "365 days (1 year)" },
];
export const SERVER_SOFTWARE = [
  { code: "1", name: "OTHER" },
  { code: "2", name: "AOL" },
  { code: "3", name: "Apache-ModSSL" },
  { code: "4", name: "Apache-SSL (Ben-SSL, not Stronghold)" },
  { code: "5", name: "C2Net Stronghold" },
  { code: "6", name: "Cisco 3000 Series VPN Concentrator" },
  { code: "7", name: "Citrix" },
  { code: "8", name: "Cobalt Raq" },
  { code: "9", name: "Covalent Server Software" },
  { code: "10", name: "Ensim" },
  { code: "11", name: "HSphere" },
  { code: "12", name: "IBM HTTP Server" },
  { code: "13", name: "IBM Internet Connection Server" },
  { code: "14", name: "iPlanet" },
  { code: "15", name: "Java Web Server" },
  { code: "16", name: "Lotus Domino" },
  { code: "17", name: "Lotus Domino Go!" },
  { code: "18", name: "Microsoft IIS 1.x to 4.x" },
  { code: "19", name: "Microsoft IIS 5.x to 6.x" },
  { code: "20", name: "Microsoft IIS 7.x+" },
  { code: "21", name: "Netscape Enterprise Server" },
  { code: "22", name: "Netscape FastTrack" },
  { code: "23", name: "Novell Web Server" },
  { code: "24", name: "Oracle" },
  { code: "25", name: "Plesk" },
  { code: "26", name: "Quid Pro Quo" },
  { code: "27", name: "R3 SSL Server" },
  { code: "28", name: "Raven SSL" },
  { code: "29", name: "RedHat Linux" },
  { code: "30", name: "SAP Web Application Server" },
  { code: "31", name: "Tomcat" },
  { code: "32", name: "Website Professional" },
  { code: "33", name: "WebStar 4.x+" },
  { code: "34", name: "WebTen (Tenon)" },
  { code: "35", name: "WHM/CPanel" },
  { code: "36", name: "Zeus Web Server" },
  { code: "37", name: "Nginx" },
  { code: "38", name: "Heroku" },
  { code: "39", name: "Amazon Load Balancer" },
];
